#pragma once
#include <cstdint>
#include "rol_helpers.h"

// ---------------------------------------------------------------------------
// Obfuscated syscall number table
//
// AUTO-GENERATED by build.py — do not edit by hand.
// Target OS: Windows 10 / 22H2
//
// Decode formula:  sysnum = ROL32(encoded ^ xor_key, 7) + addend
// Encode formula:  encoded = ROR32((sysnum - addend) & 0xFFFFFFFF, 7) ^ xor_key
// ---------------------------------------------------------------------------

namespace SyscallTable
{
    // NtQuerySystemInformation — sysnum 0x36 (54) on Windows 10 / 22H2
    constexpr uint32_t NtQSI_encoded = 0x4A63C24DUL;  // verified ✓
    constexpr uint32_t NtQSI_xor     = 0x739C3D8CUL;
    constexpr int32_t  NtQSI_addend  = 0x1F9A;
    // NtAllocateVirtualMemory — sysnum 0x18 (24) on Windows 10 / 22H2
    constexpr uint32_t NtAVM_encoded = 0x5DC12E7FUL;  // verified ✓
    constexpr uint32_t NtAVM_xor     = 0xBE3ED1F2UL;
    constexpr int32_t  NtAVM_addend  = 0x3927;
    // NtFreeVirtualMemory — sysnum 0x1E (30) on Windows 10 / 22H2
    constexpr uint32_t NtFVM_encoded = 0x551F3377UL;  // verified ✓
    constexpr uint32_t NtFVM_xor     = 0xAB1F3330UL;
    constexpr int32_t  NtFVM_addend  = -0x23E1;
    // NtWriteVirtualMemory — sysnum 0x3A (58) on Windows 10 / 22H2
    constexpr uint32_t NtWVM_encoded = 0x763E301DUL;  // verified ✓
    constexpr uint32_t NtWVM_xor     = 0x25C1CF6FUL;
    constexpr int32_t  NtWVM_addend  = 0x4711;
    // NtClose — sysnum 0x0F (15) on Windows 10 / 22H2
    constexpr uint32_t NtClose_encoded = 0xE879871AUL;  // verified ✓
    constexpr uint32_t NtClose_xor     = 0xF279872DUL;
    constexpr int32_t  NtClose_addend  = -0x1B7E;

    // -----------------------------------------------------------------------
    // Runtime resolution — call once from IndirectSyscall::init()
    // -----------------------------------------------------------------------
    struct ResolvedNumbers
    {
        uint32_t NtQuerySystemInformation;
        uint32_t NtAllocateVirtualMemory;
        uint32_t NtFreeVirtualMemory;
        uint32_t NtWriteVirtualMemory;
        uint32_t NtClose;
    };

    inline ResolvedNumbers resolve()
    {
        ResolvedNumbers r{};
        r.NtQuerySystemInformation = decode_sysnum(NtQSI_encoded,   NtQSI_xor,   NtQSI_addend);
        r.NtAllocateVirtualMemory  = decode_sysnum(NtAVM_encoded,   NtAVM_xor,   NtAVM_addend);
        r.NtFreeVirtualMemory      = decode_sysnum(NtFVM_encoded,   NtFVM_xor,   NtFVM_addend);
        r.NtWriteVirtualMemory     = decode_sysnum(NtWVM_encoded,   NtWVM_xor,   NtWVM_addend);
        r.NtClose                  = decode_sysnum(NtClose_encoded, NtClose_xor, NtClose_addend);
        return r;
    }

} // namespace SyscallTable
